[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = { workspace = true }
actix-files = { workspace = true }
actix-web = { workspace = true }
anyhow = { workspace = true }
app = { path = "../app" }
clap = { workspace = true }
derive_more = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
