[workspace]
resolver = "3"
members = ["src/*"]

[workspace.dependencies]
actix-cors = { version = "0.7.1" }
actix-files = { version = "0.6.6" }
actix-web = { version = "4.8.0" }
anyhow = { version = "1.0.102" }
bytemuck = { version = "1.25.0", features = ["derive"] }
clap = { version = "4.5.4", features = ["derive"] }
dashmap = { version = "6.0.1" }
derive_more = { version = "2.1.1", features = ["as_ref", "debug", "display", "from", "into"] }
diesel = { version = "2.3.9", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.3.2" }
dotenvy = { version = "0.15.7" }
dyn-clone = { version = "1.0.20" }
env_logger = { version = "0.11.3" }
futures-util = { version = "0.3.32" }
indicatif = { version = "0.18.4" }
lazy_static = { version = "1.5.0" }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
log = { version = "0.4.22" }
num = { version = "0.4" }
num-derive = { version = "0.4" }
num-traits = { version = "0.2" }
regex = { version = "1.10.5" }
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
test-log = { version = "0.2.20" }
thiserror = { version = "1.0.63" }
threadpool = { version = "1.8.1" }
time = { version = "0.3.47", features = ["serde", "parsing", "formatting"] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }
which = { version = "8.0.2" }

[profile.release-with-debug]
inherits = "release"
debug = true
