[workspace]
resolver = "3"
members = ["src/*"]

[workspace.dependencies]
actix-files = { version = "0.6.6" }
actix-web = { version = "4.8.0" }
anyhow = { version = "1.0.102" }
bytemuck = { version = "1.25.0", features = ["derive"] }
clap = { version = "4.5.4", features = ["derive"] }
dashmap = { version = "6.0.1" }
derive_more = { version = "0.99.18" }
env_logger = { version = "0.11.3" }
futures-util = { version = "0.3.32" }
indicatif = { version = "0.18.4" }
lazy_static = { version = "1.5.0" }
log = { version = "0.4.22" }
num = { version = "0.4" }
num-derive = { version = "0.4" }
num-traits = { version = "0.2" }
regex = { version = "1.10.5" }
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0.63" }
threadpool = { version = "1.8.1" }
time = { version = "0.3.47", features = ["serde"] }

[profile.release-with-debug]
inherits = "release"
debug = true
