[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
app = { path = "../app" }
clap = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
