[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
dashmap = { workspace = true }
diesel = { version = "2.3.9", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.3.2" }
lazy_static = { workspace = true }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
log = { workspace = true }
num = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
threadpool = { workspace = true }
time = { workspace = true }
