[package]
name = "headless"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
app = { path = "../app" }
clap = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
